/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Usuario
 */
public class Bienvenida extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bienvenida.class.getName());

    /**
     * Creates new form Bienvenida
     */
    public Bienvenida() {
        initComponents();
        setSize(600, 400);
        setLocationRelativeTo(null); 
        setResizable(false);
        
    // Texto con nombres y cédulas en varias líneas
    labAutores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    labAutores.setText(
        "<html><center>"
        + "ERP con IA<br>"
        + "Aitana Alvarez - 340201<br>"
        + "Francisco Bonanni - 299134"
        + "</center></html>"
    );

    // Timer: después de 4 segundos (entre 3 y 5) abre el menú de inicio
    javax.swing.Timer timer = new javax.swing.Timer(4000, e -> {
        dispose();                    // cierro la bienvenida
        new MenuInicio().setVisible(true);  // abro ventana con 3 botones
    });
    timer.setRepeats(false);
    timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBienvenida = new javax.swing.JPanel();
        labAutores = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBienvenida.setBackground(new java.awt.Color(204, 204, 255));
        panelBienvenida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labAutores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labAutores.setText("Nombres: Aitana Alvarez - 340201 | Francisco Bonanni - 299134");
        panelBienvenida.add(labAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, -1, -1));

        icon.setIcon(new javax.swing.ImageIcon("C:\\proyectos\\Obligatorio2-P2\\src\\resources\\logo.png")); // NOI18N
        panelBienvenida.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 900, 500));

        getContentPane().add(panelBienvenida, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Bienvenida().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon;
    private javax.swing.JLabel labAutores;
    private javax.swing.JPanel panelBienvenida;
    // End of variables declaration//GEN-END:variables
}
