/*
 Aitana Alvarez 340201
 Francisco Bonanni 299134
 */
package view;

import model.Sistema;
import controller.*;

/**
 *
 * @author Usuario
 */
public class MenuInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuInicio.class.getName());
    
    private final Sistema sistema = Sistema.getInstancia();

    /**
     * Creates new form MenuInicio
     */
    public MenuInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSistNuevo = new javax.swing.JButton();
        btnSistGuardado = new javax.swing.JButton();
        btnSistPre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");

        btnSistNuevo.setText("Sistema nuevo");
        btnSistNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistNuevoActionPerformed(evt);
            }
        });

        btnSistGuardado.setText("Sistema guardado");
        btnSistGuardado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistGuardadoActionPerformed(evt);
            }
        });

        btnSistPre.setText("Sistema con datos precargados");
        btnSistPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistPreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSistNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSistGuardado)
                .addGap(18, 18, 18)
                .addComponent(btnSistPre)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSistNuevo)
                    .addComponent(btnSistGuardado)
                    .addComponent(btnSistPre))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSistNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistNuevoActionPerformed
        sistema.iniciarSistemaVacio();
        abrirMenuPrincipal();
    }//GEN-LAST:event_btnSistNuevoActionPerformed

    private void btnSistGuardadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistGuardadoActionPerformed
        sistema.iniciarSistemaGuardado();
        abrirMenuPrincipal();
    }//GEN-LAST:event_btnSistGuardadoActionPerformed

    private void btnSistPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistPreActionPerformed
        sistema.iniciarSistemaConDatosPrecargados();
        abrirMenuPrincipal();
    }//GEN-LAST:event_btnSistPreActionPerformed
                                                      

    private void abrirMenuPrincipal() {
        Principal p = new Principal();
        new ControladorArea(p);
        new ControladorManager(p);
        new ControladorEmpleado(p);
        new ControladorReporteMovimiento(p);
        new ControladorReporteInteligente(p);
        p.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSistGuardado;
    private javax.swing.JButton btnSistNuevo;
    private javax.swing.JButton btnSistPre;
    // End of variables declaration//GEN-END:variables
}
