/*
 Aitana Alvarez 340201
 Francisco Bonanni 299134
 */
package view;

public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        menuAreas = new javax.swing.JMenu();
        altaArea = new javax.swing.JMenuItem();
        bajaArea = new javax.swing.JMenuItem();
        modifiacionArea = new javax.swing.JMenuItem();
        areaMov = new javax.swing.JMenuItem();
        menuManagers = new javax.swing.JMenu();
        altaMan = new javax.swing.JMenuItem();
        bajaMan = new javax.swing.JMenuItem();
        modificacionMan = new javax.swing.JMenuItem();
        menuEmpleados = new javax.swing.JMenu();
        altaEmp = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        inteligente = new javax.swing.JMenuItem();
        estado = new javax.swing.JMenuItem();
        repoMov = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ERP Empresarial");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuAreas.setText("Áreas");

        altaArea.setText("Alta");
        menuAreas.add(altaArea);

        bajaArea.setText("Baja");
        menuAreas.add(bajaArea);

        modifiacionArea.setText("Modificación");
        menuAreas.add(modifiacionArea);

        areaMov.setText("Realizar movimiento");
        menuAreas.add(areaMov);

        menuPrincipal.add(menuAreas);

        menuManagers.setText("Managers");

        altaMan.setText("Alta");
        menuManagers.add(altaMan);

        bajaMan.setText("Baja");
        bajaMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaManActionPerformed(evt);
            }
        });
        menuManagers.add(bajaMan);

        modificacionMan.setText("Modificación");
        menuManagers.add(modificacionMan);

        menuPrincipal.add(menuManagers);

        menuEmpleados.setText("Empleados");

        altaEmp.setText("Alta");
        menuEmpleados.add(altaEmp);

        menuPrincipal.add(menuEmpleados);

        menuReportes.setText("Reportes");

        inteligente.setText("Reporte inteligente");
        menuReportes.add(inteligente);

        estado.setText("Reporte de estado de áreas");
        menuReportes.add(estado);

        repoMov.setText("Reporte de movimientos");
        menuReportes.add(repoMov);

        menuPrincipal.add(menuReportes);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bajaManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaManActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bajaManActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }
    
    public javax.swing.JMenuItem getAltaMan() {return altaMan;}
    public javax.swing.JMenuItem getBajaMan() {return bajaMan;}
    public javax.swing.JMenuItem getModificacionMan() {return modificacionMan;}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem altaArea;
    private javax.swing.JMenuItem altaEmp;
    private javax.swing.JMenuItem altaMan;
    private javax.swing.JMenuItem areaMov;
    private javax.swing.JMenuItem bajaArea;
    private javax.swing.JMenuItem bajaMan;
    private javax.swing.JMenuItem estado;
    private javax.swing.JMenuItem inteligente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAreas;
    private javax.swing.JMenu menuEmpleados;
    private javax.swing.JMenu menuManagers;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenuItem modifiacionArea;
    private javax.swing.JMenuItem modificacionMan;
    private javax.swing.JMenuItem repoMov;
    // End of variables declaration//GEN-END:variables
}
