/*
 Aitana Alvarez 340201
 Francisco Bonanni 299134
 */
package view;

import model.Sistema;
import model.Observer;
import model.Empleado;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

public class ReporteInteligente extends javax.swing.JDialog implements Observer {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReporteInteligente.class.getName());

    /**
     * Creates new form ReporteInteligente
     */
    public ReporteInteligente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labTitulo = new javax.swing.JLabel();
        labArea = new javax.swing.JLabel();
        boxOrigen = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        boxEmpleado = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        boxDestino = new javax.swing.JComboBox<>();
        labIcono = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        labResultado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textResult = new javax.swing.JTextArea();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labTitulo.setText("Reporte inteligente");

        labArea.setText("Area:");

        boxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Empleado:");

        boxEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxEmpleadoActionPerformed(evt);
            }
        });

        jLabel2.setText("Destino:");

        boxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGenerar.setText("Generar reporte");

        labResultado.setText("Resultado:");

        textResult.setColumns(20);
        textResult.setRows(5);
        jScrollPane1.setViewportView(textResult);

        btnCerrar.setText("Cerrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(288, Short.MAX_VALUE)
                        .addComponent(btnGenerar)))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(labTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labResultado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labArea, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTitulo)
                .addGap(5, 5, 5)
                .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labArea)
                            .addComponent(boxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(boxEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(boxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(labResultado))
                    .addComponent(labIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrar)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ReporteInteligente dialog = new ReporteInteligente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public javax.swing.JComboBox<String> getBoxOrigen() { return boxOrigen; }
    public javax.swing.JComboBox<String> getBoxDestino() { return boxDestino; }
    public javax.swing.JComboBox<String> getBoxEmpleado() { return boxEmpleado; }
    public javax.swing.JButton getBtnGenerar() { return btnGenerar; }
    public javax.swing.JButton getBtnCerrar() { return btnCerrar; }
    public javax.swing.JTextArea getTextResult() { return textResult; }
    public javax.swing.JLabel getLabIcono() { return labIcono; }
    
    public void mostrarResultado(String texto) {
        textResult.setText(texto);
    }
    
    public void setIconoCargando() {
        labIcono.setIcon(new ImageIcon(getClass().getResource("/resources/icono-cargando.gif")));
    }

    public void setIconoExito() {
        labIcono.setIcon(new ImageIcon(getClass().getResource("/resources/icono-exito.png")));
    }

    public void setIconoError() {
        labIcono.setIcon(new ImageIcon(getClass().getResource("/resources/icono-error.png")));
    }

    public void cargarEmpleadosSegunOrigen() {
        var sistema = Sistema.getInstancia();
        String nombreArea = (String) boxOrigen.getSelectedItem();

        if (nombreArea != null) {
            var empleados = sistema.getEmpleadosEnArea(nombreArea);

            String[] nombres = new String[empleados.size()];
            for (int i = 0; i < empleados.size(); i++) {
                nombres[i] = empleados.get(i).getNombre();
            }

            boxEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(nombres));
        } else {
            boxEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[0]));
        }
    }
    
    @Override
    public void actualizar() {
        Sistema sistema = Sistema.getInstancia();

        // --- reload areas ---
        var areas = sistema.getAreas();

        String selectedOrigen = (String) boxOrigen.getSelectedItem();
        String selectedDestino = (String) boxDestino.getSelectedItem();
        String selectedEmpleado = (String) boxEmpleado.getSelectedItem();

        // build area names
        String[] nombresAreas = new String[areas.size()];
        for (int i = 0; i < areas.size(); i++) {
            nombresAreas[i] = areas.get(i).getNombre();
        }

        boxOrigen.setModel(new DefaultComboBoxModel<>(nombresAreas));
        boxDestino.setModel(new DefaultComboBoxModel<>(nombresAreas));

        // try to restore previous selections if still valid
        if (selectedOrigen != null) {
            boxOrigen.setSelectedItem(selectedOrigen);
        }
        if (selectedDestino != null) {
            boxDestino.setSelectedItem(selectedDestino);
        }

        // --- reload employees based on selected origin area ---
        String origenActual = (String) boxOrigen.getSelectedItem();
        ArrayList<Empleado> empleadosFiltrados = new ArrayList<>();

        for (Empleado e : sistema.getEmpleados()) {
            if (e.getArea() != null && e.getArea().getNombre().equals(origenActual)) {
                empleadosFiltrados.add(e);
            }
        }

        String[] nombresEmpleados = new String[empleadosFiltrados.size()];
        for (int i = 0; i < empleadosFiltrados.size(); i++) {
            nombresEmpleados[i] = empleadosFiltrados.get(i).getNombre();
        }

        boxEmpleado.setModel(new DefaultComboBoxModel<>(nombresEmpleados));

        // restore selected employee if still available
        if (selectedEmpleado != null) {
            boxEmpleado.setSelectedItem(selectedEmpleado);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxDestino;
    private javax.swing.JComboBox<String> boxEmpleado;
    private javax.swing.JComboBox<String> boxOrigen;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labArea;
    private javax.swing.JLabel labIcono;
    private javax.swing.JLabel labResultado;
    private javax.swing.JLabel labTitulo;
    private javax.swing.JTextArea textResult;
    // End of variables declaration//GEN-END:variables
}
