/*
 Aitana Alvarez 340201
 Francisco Bonanni 299134
 */

package view;

import java.awt.Color;
import java.awt.Insets;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;

import model.Area;
import model.Empleado;
import model.Sistema;
import model.Observer;

public class ReporteEstadoAreas extends javax.swing.JDialog implements Observer {
    
    private final Sistema sistema = Sistema.getInstancia();
    private List<Area> areasOrdenadas = new ArrayList<>();
    private Area areaSeleccionada;

   public ReporteEstadoAreas(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    
    sistema.agregarObserver(this);

    panelArea.setLayout(new java.awt.GridLayout(0, 1, 5, 5));
    panelEmpleados.setLayout(new java.awt.GridLayout(0, 3, 5, 5));

    refrescar();
    addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            sistema.quitarObserver(ReporteEstadoAreas.this);
         }
        });
}
@Override
public void actualizar() {
    refrescar();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labTitulo = new javax.swing.JLabel();
        labAreas = new javax.swing.JLabel();
        labSel = new javax.swing.JLabel();
        labAreaSel = new javax.swing.JLabel();
        labPor = new javax.swing.JLabel();
        scrollPanelArea = new javax.swing.JScrollPane();
        panelArea = new javax.swing.JPanel();
        scrollPanelEmpleado = new javax.swing.JScrollPane();
        panelEmpleados = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labTitulo.setText("Estado de áreas");

        labAreas.setText("Áreas");

        labSel.setText("Empleados del área seleccionada");

        labAreaSel.setText("Área seleccionada: ");

        labPor.setText("Presupuesto asignado:  %");

        panelArea.setLayout(new java.awt.GridLayout(0, 1));
        scrollPanelArea.setViewportView(panelArea);

        panelEmpleados.setLayout(new java.awt.GridLayout(0, 3));
        scrollPanelEmpleado.setViewportView(panelEmpleados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(labTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labAreaSel)
                        .addGap(57, 57, 57)
                        .addComponent(labPor)
                        .addContainerGap(86, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPanelArea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labSel)
                            .addComponent(scrollPanelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labSel)
                    .addComponent(labAreas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPanelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labAreaSel)
                            .addComponent(labPor)))
                    .addComponent(scrollPanelArea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            ReporteEstadoAreas dialog = new ReporteEstadoAreas(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });

    }
    private void refrescar() {
        areasOrdenadas = new ArrayList<>(sistema.getAreas());

        
        Collections.sort(areasOrdenadas, (a1, a2) -> {
            double p1 = calcularPorcentajeArea(a1);
            double p2 = calcularPorcentajeArea(a2);
            return Double.compare(p2, p1); // orden decreciente
        });

        construirBotonesAreas();

        if (!areasOrdenadas.isEmpty()) {
            if (areaSeleccionada == null || !areasOrdenadas.contains(areaSeleccionada)) {
                areaSeleccionada = areasOrdenadas.get(0);
            }
            seleccionarArea(areaSeleccionada);
        } else {
            areaSeleccionada = null;
            
            labAreaSel.setText("Sin áreas");
            panelEmpleados.removeAll();
            panelEmpleados.revalidate();
            panelEmpleados.repaint();
        }
    }

    private void construirBotonesAreas() {
        panelArea.removeAll();

        for (Area area : areasOrdenadas) {
            double porcentaje = calcularPorcentajeArea(area);

            JButton btn = new JButton(area.getNombre());
            btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            btn.setMargin(new Insets(5, 10, 5, 10));
            btn.setBackground(colorPorPorcentaje(porcentaje));
            btn.setOpaque(true);
            btn.setBorderPainted(false);

            btn.addActionListener(e -> seleccionarArea(area));

            panelArea.add(btn);
        }

        panelArea.revalidate();
        panelArea.repaint();
    }
    private double calcularPorcentajeArea(Area area) {
        double presupuesto = area.getPresupuesto();
        if (presupuesto <= 0) {
            return 0;
        }

        double totalSalariosAnuales = 0;
        for (Empleado e : area.getEmpleados()) {
            totalSalariosAnuales += e.getSalario() * 12; 
        }

        return (totalSalariosAnuales / presupuesto) * 100.0;
    }
    private Color colorPorPorcentaje(double porcentaje) {
        if (porcentaje > 90) {
            return Color.RED;
        } else if (porcentaje >= 70) {
            return Color.YELLOW;
        } else {
            return Color.LIGHT_GRAY;
        }
    }
    private void seleccionarArea(Area area) {
        this.areaSeleccionada = area;

        double p = calcularPorcentajeArea(area);
        labAreaSel.setText(
                area.getNombre() + " " + String.format("%.0f%%", p)
        );

        cargarEmpleados(area);
    }

    private void cargarEmpleados(Area area) {
        panelEmpleados.removeAll();

        List<Empleado> empleados = new ArrayList<>(area.getEmpleados());
        // ordeno por nombre
        empleados.sort(Comparator.comparing(Empleado::getNombre, String.CASE_INSENSITIVE_ORDER));

        if (empleados.isEmpty()) {
            panelEmpleados.revalidate();
            panelEmpleados.repaint();
            return;
        }

        double minSal = empleados.stream().mapToDouble(Empleado::getSalario).min().orElse(0);
        double maxSal = empleados.stream().mapToDouble(Empleado::getSalario).max().orElse(0);

        for (Empleado e : empleados) {
            JButton btn = new JButton(e.getNombre());
            btn.setMargin(new Insets(5, 10, 5, 10));
            btn.setForeground(Color.WHITE);
            btn.setBackground(colorPorSalario(e.getSalario(), minSal, maxSal));
            btn.setOpaque(true);
            btn.setBorderPainted(false);

            btn.addActionListener(ev -> mostrarDetalleEmpleado(e));

            panelEmpleados.add(btn);
        }

        panelEmpleados.revalidate();
        panelEmpleados.repaint();
    }

    private Color colorPorSalario(double salario, double min, double max) {
        if (max <= min) { // todos cobran lo mismo
            return new Color(0, 0, 255); 
        }
        double factor = (salario - min) / (max - min); 
        int blue = (int) Math.round(255 * factor);     
        return new Color(0, 0, blue);
    }
    private void mostrarDetalleEmpleado(Empleado e) {
        StringBuilder sb = new StringBuilder();
        sb.append("Nombre: ").append(e.getNombre()).append("\n");
        sb.append("Cédula: ").append(e.getCedula()).append("\n");
        sb.append("Celular: ").append(e.getCelular()).append("\n");
        sb.append("Salario mensual: ").append(String.format("%.2f", e.getSalario())).append("\n");

        if (e.getManager() != null) {
            sb.append("Manager: ").append(e.getManager().getNombre()).append("\n");
        }
        if (e.getArea() != null) {
            sb.append("Área: ").append(e.getArea().getNombre()).append("\n");
        }

        sb.append("\nCV:\n").append(e.getCv());

        JOptionPane.showMessageDialog(
                this,
                sb.toString(),
                "Datos del empleado",
                JOptionPane.INFORMATION_MESSAGE
        );
    }    
   public void cargarListadoAreas(List<Area> lista, ActionListener listener) {
        panelArea.removeAll();

        for (Area area : lista) {
            double porcentaje = calcularPorcentajeArea(area);

            JButton btn = new JButton(area.getNombre());
            btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            btn.setMargin(new Insets(5, 10, 5, 10));
            btn.setBackground(colorPorPorcentaje(porcentaje));
            btn.setOpaque(true);
            btn.setBorderPainted(false);

            btn.putClientProperty("obj", area);  // para que el controlador sepa qué área es
            btn.addActionListener(listener);

            panelArea.add(btn);
        }

        panelArea.revalidate();
        panelArea.repaint();
    }

    public void mostrarAreaSeleccionada(Area area, double porcentaje) {
        this.areaSeleccionada = area;
        labAreaSel.setText("Área seleccionada: " + area.getNombre());
        labPor.setText("Presupuesto asignado: " + String.format("%.0f%%", porcentaje));
    }

    public void cargarEmpleados(List<Empleado> lista, ActionListener listener) {
        panelEmpleados.removeAll();

        if (lista == null || lista.isEmpty()) {
            panelEmpleados.revalidate();
            panelEmpleados.repaint();
            return;
        }

        double minSal = lista.stream().mapToDouble(Empleado::getSalario).min().orElse(0);
        double maxSal = lista.stream().mapToDouble(Empleado::getSalario).max().orElse(0);

        for (Empleado e : lista) {
            JButton btn = new JButton(e.getNombre());
            btn.setMargin(new Insets(5, 10, 5, 10));
            btn.setForeground(Color.WHITE);
            btn.setBackground(colorPorSalario(e.getSalario(), minSal, maxSal));
            btn.setOpaque(true);
            btn.setBorderPainted(false);

            btn.putClientProperty("obj", e);  // el controlador recibe el empleado
            btn.addActionListener(listener);

            panelEmpleados.add(btn);
        }

        panelEmpleados.revalidate();
        panelEmpleados.repaint();
    }

    public void mostrarPopupEmpleado(Empleado e) {
        mostrarDetalleEmpleado(e);
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labAreaSel;
    private javax.swing.JLabel labAreas;
    private javax.swing.JLabel labPor;
    private javax.swing.JLabel labSel;
    private javax.swing.JLabel labTitulo;
    private javax.swing.JPanel panelArea;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JScrollPane scrollPanelArea;
    private javax.swing.JScrollPane scrollPanelEmpleado;
    // End of variables declaration//GEN-END:variables
}